# Generated by Django 5.1.2 on 2024-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='no_seleccionable',
            field=models.BooleanField(default=False),
        ),
    ]
